apiVersion: v1
kind: Service
metadata:
  name: static-site-app-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: spa-game-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30002